# Generated by Django 4.2.1 on 2023-07-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored_activities_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Types',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='types',
            field=models.CharField(choices=[], max_length=20),
        ),
    ]
