# Generated by Django 4.2.1 on 2023-07-04 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored_activities_app', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activities_fetched_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_fetch_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
