# Generated by Django 4.2.1 on 2023-07-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bored_activities_app', '0006_remove_userprofile_activities_fetched_today_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivityinfo',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='useractivityinfo',
            table='user_activity',
        ),
    ]
