# Generated by Django 4.2.1 on 2023-07-04 09:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bored_activities_app', '0007_alter_useractivityinfo_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserActivityInfo',
            new_name='UserActivity',
        ),
    ]
