# Generated by Django 4.2.1 on 2023-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored_activities_app', '0008_rename_useractivityinfo_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
