# Generated by Django 4.2.1 on 2023-07-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bored_activities_app', '0011_useraction_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraction',
            options={},
        ),
        migrations.AlterModelTable(
            name='useraction',
            table=None,
        ),
    ]
