# Generated by Django 4.2.1 on 2023-07-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bored_activities_app', '0015_useractions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractions',
            options={'managed': False},
        ),
    ]
